### ISSUE TITLE
On MacOS malloc.h is missing

### ISSUE THREAD

**Issue by alexsaezm** [KVault/NESulator#35]
I made this workaround. But I don't have a Windows machine right now. Does it work?

https://github.com/KVault/NESulator/blob/a6135ef9f82b3d1e592308b1d48607a8a4f89c5b/src/utils/ppu_utils.h#L6-L14

**Comment by santanor** [comment]
We've used `malloc` before, on the ROM reading that includes "stdlib.h" so we can just use that instead. It should be fine

**Comment by alexsaezm** [comment]
`stdlib.h` instead :D
